#!/usr/bin/env bash
# ==============================================================================
#                            ~/.bashrc - Main File                              
#                                                                               
# This file is auto-generated by the generate_bashrc.sh script.                 
# Do not edit this file directly, as your changes will be overwritten.          
# Instead, edit the individual .sh files in /home/simon/scripts/bashrc          
# and then re-run the generation script.                                        
#                                                                               
# Generated on: 2025-05-27 20:35:39 CEST                                    
# ==============================================================================


# ==============================================================================
# START OF CONFIGURATION FROM: alias.sh
# ==============================================================================

#!/bin/bash

alias ll='ls -salh --color=auto --hyperlink=auto'
alias c='clear'
alias s='sudo'
alias h='history'

# installing packages on arch
alias i='sudo pacman -Syu'

# removal protection
alias rm='rm -I'

# dstask aliases
alias d='dstask'
alias da='dstask add'
alias ds='dstask start'
alias dd='dstask done'
alias dc='dstask context'
alias dm='dstask modify'
alias dl='dstask log'
alias de='dstask edit'
alias dn='dstask note'
alias dsync='dstask sync'
alias dnote='dstask note'
alias dstop='dstask stop'
alias drm='dstask remove'


# ==============================================================================
# End of alias.sh
# ==============================================================================


# ==============================================================================
# START OF CONFIGURATION FROM: atuin.sh
# ==============================================================================

#!/bin/bash

if [ -d "$HOME/.atuin/bin" ]; then
	. "$HOME/.atuin/bin/env"

	[[ -f ~/.bash-preexec.sh ]] && source ~/.bash-preexec.sh
	eval "$(atuin init bash --disable-up-arrow)"
fi

# ==============================================================================
# End of atuin.sh
# ==============================================================================


# ==============================================================================
# START OF CONFIGURATION FROM: color.sh
# ==============================================================================

#!/bin/bash

# COLOR SETTINGS
# uncomment for a colored prompt, if the terminal has the capability; turned
# off by default to not distract the user: the focus in a terminal window
# should be on the output of commands, not on the prompt
force_color_prompt=yes

if [ -n "$force_color_prompt" ]; then
    if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
    # We have color support; assume it's compliant with Ecma-48
    # (ISO/IEC-6429). (Lack of such support is extremely rare, and such
    # a case would tend to support setf rather than setaf.)
    color_prompt=yes
    else
    color_prompt=
    fi
fi

if [ "$color_prompt" = yes ]; then
    PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
else
    PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '
fi
unset color_prompt force_color_prompt

# If this is an xterm set the title to user@host:dir
case "$TERM" in
xterm*|rxvt*)
    PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]$PS1"
    ;;
*)
    ;;
esac

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls -salh --color=auto --hyperlink=auto'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi


# ==============================================================================
# End of color.sh
# ==============================================================================


# ==============================================================================
# START OF CONFIGURATION FROM: dstask.sh
# ==============================================================================

#!/bin/bash

# dstask aliases
alias d='dstask next'
alias da='dstask add'
alias ds='dstask start'
alias dd='dstask done'
alias dc='dstask context'
alias dm='dstask modify'
alias dl='dstask log'
alias de='dstask edit'
alias dn='dstask note'
alias dsync='dstask sync'
alias dnote='dstask note'
alias dstop='dstask stop'
alias drm='dstask remove'


# ==============================================================================
# End of dstask.sh
# ==============================================================================


# ==============================================================================
# START OF CONFIGURATION FROM: git.sh
# ==============================================================================

#!/bin/bash

# commit faster
function g() {
		git add .
		git commit -m "$1"
		git push
}

alias lg='lazygit'
alias gs='git status'
alias ga='git add'
alias gc='git commit'
alias gp='git push'


# ==============================================================================
# End of git.sh
# ==============================================================================


# ==============================================================================
# START OF CONFIGURATION FROM: languages.sh
# ==============================================================================

#!/bin/bash

if [ -d "/usr/local/go/bin" ]; then
	export PATH=$PATH:/usr/local/go/bin
fi

if [ -d "/usr/local/zig" ]; then
	export PATH=$PATH:/usr/local/zig
fi

if [ -d "$HOME/.nvm" ]; then
	export NVM_DIR="$HOME/.nvm"
	[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
	[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
fi

if [ -d "$HOME/gems" ]; then
		export GEM_HOME="$HOME/gems"
		export PATH="$HOME/gems/bin:$PATH"
fi

if [ -d "$HOME/.dotnet" ]; then
	export PATH=$PATH:/home/simon/.dotnet
fi


if [ -d "$HOME/.cargo" ]; then
    . "$HOME/.cargo/env"
fi

if [ -d "$HOME/go/bin" ]; then
    export PATH=$PATH:$HOME/go/bin
fi

if [ -d "$HOME/.local/bin" ]; then
		export PATH=$PATH:$HOME/.local/bin
fi

if [ -d "$HOME/.bun/" ]; then
	export BUN_INSTALL="$HOME/.bun"
	export PATH="$BUN_INSTALL/bin:$PATH"
fi

if ! [[ "$PATH" =~ "$HOME/.local/bin:$HOME/bin:" ]]; then
    PATH="$HOME/.local/bin:$HOME/bin:$PATH"
fi


# ==============================================================================
# End of languages.sh
# ==============================================================================


# ==============================================================================
# START OF CONFIGURATION FROM: nvim.sh
# ==============================================================================

#!/bin/bash

alias e='nvim'
alias vim='nvim'
alias v='nvim'

export MANPAGER='nvim +Man!'
export EDITOR="nvim"
export VISUAL="nvim"

# ==============================================================================
# End of nvim.sh
# ==============================================================================


# ==============================================================================
# START OF CONFIGURATION FROM: path.sh
# ==============================================================================

#!/bin/bash

if [ -d "$HOME/bin" ]; then
	PATH="$HOME/bin:$PATH"
	export PATH
fi


# export SSH_AUTH_SOCK="${XDG_RUNTIME_DIR}/ssh-agent.socket"

# ==============================================================================
# End of path.sh
# ==============================================================================


# ==============================================================================
# START OF CONFIGURATION FROM: rename.sh
# ==============================================================================

#!/bin/bash

# This allows you to change a part of a filename to another part.
function rename_part() {
  # First parse optional flags
  local recursive=false
  while [[ "$1" == "-"* ]]; do
    case "$1" in
      -r|--recursive)
        recursive=true
        shift
        ;;
      *)
        echo "Unknown option: $1"
        echo "Usage: rename_part [-r|--recursive] <old> <new>"
        return 1
        ;;
    esac
  done

  # After flags, the first two positional args are the 'old' and 'new' substrings
  local old="$1"
  local new="$2"

  if [[ -z "$old" || -z "$new" ]]; then
    echo "Usage: rename_part [-r|--recursive] <old> <new>"
    return 1
  fi

  if [ "$recursive" = true ]; then
    # Recursively find all files containing 'old' in the filename
    # -print0 and read -r -d '' handle spaces and special chars in filenames
    find . -type f -name "*${old}*" -print0 |
    while IFS= read -r -d '' file; do
      local dir
      local base
      dir="$(dirname "$file")"
      base="$(basename "$file")"

      # Replace 'old' with 'new' in the filename
      local newfile="${base//$old/$new}"

      # Perform the rename
      mv -v -- "$file" "$dir/$newfile"
    done
  else
    # Non-recursive: only look in the current directory
    for file in *"$old"*; do
      [[ -e "$file" ]] || continue  # Skip if no match
      local newfile="${file//$old/$new}"
      mv -v -- "$file" "$newfile"
    done
  fi
}


# ==============================================================================
# End of rename.sh
# ==============================================================================


# ==============================================================================
# START OF CONFIGURATION FROM: root.sh
# ==============================================================================

#!/usr/bin/env bash

export BASH_ENV="~/.bash_env"

# Source global definitions
if [ -f /etc/bashrc ]; then
    . /etc/bashrc
fi

if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
fi

# ==============================================================================
# End of root.sh
# ==============================================================================


# ==============================================================================
# START OF CONFIGURATION FROM: tmux.sh
# ==============================================================================

#!/bin/bash

function n() {
    if [ -z "$1" ]; then
        echo "Usage: n <session_name|directory>"
        return 1
    fi

    # If argument is a directory, use basename as session name
    if [ -d "$1" ]; then
        session_name=$(basename "$1")
        work_dir=$(realpath "$1")
    else
        session_name="$1"
        work_dir="$PWD"
    fi

    if [ -n "$TMUX" ]; then
        tmux has-session -t "$session_name" 2>/dev/null
        if [ $? != 0 ]; then
            tmux new-session -d -s "$session_name" -c "$work_dir"
        fi
        tmux switch-client -t "$session_name"
    else
        echo "Not inside tmux."
        return 1
    fi
}

if [ -d "$HOME/source/tmux-session-wizard-rewired/bin" ]; then
		export PATH="$HOME/source/tmux-session-wizard-rewired/bin:$PATH"
elif [ -d "$HOME/.tmux/plugins/tmux-session-wizard-rewired/bin" ]; then
		export PATH="$HOME/.tmux/plugins/tmux-session-wizard-rewired/bin:$PATH"
fi


# ==============================================================================
# End of tmux.sh
# ==============================================================================


# ==============================================================================
# START OF CONFIGURATION FROM: zoxide.sh
# ==============================================================================

#!/bin/bash

# shellcheck shell=bash

# =============================================================================
#
# Utility functions for zoxide.
#

# pwd based on the value of _ZO_RESOLVE_SYMLINKS.
function __zoxide_pwd() {
    \builtin pwd -L
}

# cd + custom logic based on the value of _ZO_ECHO.
function __zoxide_cd() {
    # shellcheck disable=SC2164
    \builtin cd -- "$@"
}

# =============================================================================
#
# Hook configuration for zoxide.
#

# Hook to add new entries to the database.
__zoxide_oldpwd="$(__zoxide_pwd)"

function __zoxide_hook() {
    \builtin local -r retval="$?"
    \builtin local pwd_tmp
    pwd_tmp="$(__zoxide_pwd)"
    if [[ ${__zoxide_oldpwd} != "${pwd_tmp}" ]]; then
        __zoxide_oldpwd="${pwd_tmp}"
        \command zoxide add -- "${__zoxide_oldpwd}"
    fi
    return "${retval}"
}

# Initialize hook.
if [[ ${PROMPT_COMMAND:=} != *'__zoxide_hook'* ]]; then
    PROMPT_COMMAND="__zoxide_hook;${PROMPT_COMMAND#;}"
fi

# =============================================================================
#
# When using zoxide with --no-cmd, alias these internal functions as desired.
#

__zoxide_z_prefix='z#'

# Jump to a directory using only keywords.
function __zoxide_z() {
    # shellcheck disable=SC2199
    if [[ $# -eq 0 ]]; then
        __zoxide_cd ~
    elif [[ $# -eq 1 && $1 == '-' ]]; then
        __zoxide_cd "${OLDPWD}"
    elif [[ $# -eq 1 && -d $1 ]]; then
        __zoxide_cd "$1"
    elif [[ $# -eq 2 && $1 == '--' ]]; then
        __zoxide_cd "$2"
    elif [[ ${@: -1} == "${__zoxide_z_prefix}"?* ]]; then
        # shellcheck disable=SC2124
        \builtin local result="${@: -1}"
        __zoxide_cd "${result:${#__zoxide_z_prefix}}"
    else
        \builtin local result
        # shellcheck disable=SC2312
        result="$(\command zoxide query --exclude "$(__zoxide_pwd)" -- "$@")" &&
            __zoxide_cd "${result}"
    fi
}

# Jump to a directory using interactive search.
function __zoxide_zi() {
    \builtin local result
    result="$(\command zoxide query --interactive -- "$@")" && __zoxide_cd "${result}"
}

# =============================================================================
#
# Commands for zoxide. Disable these using --no-cmd.
#

\builtin unalias z &>/dev/null || \builtin true
function z() {
    __zoxide_z "$@"
}

\builtin unalias zi &>/dev/null || \builtin true
function zi() {
    __zoxide_zi "$@"
}

# Load completions.
# - Bash 4.4+ is required to use `@Q`.
# - Completions require line editing. Since Bash supports only two modes of
#   line editing (`vim` and `emacs`), we check if either them is enabled.
# - Completions don't work on `dumb` terminals.
if [[ ${BASH_VERSINFO[0]:-0} -eq 4 && ${BASH_VERSINFO[1]:-0} -ge 4 || ${BASH_VERSINFO[0]:-0} -ge 5 ]] &&
    [[ :"${SHELLOPTS}": =~ :(vi|emacs): && ${TERM} != 'dumb' ]]; then
    # Use `printf '\e[5n'` to redraw line after fzf closes.
    \builtin bind '"\e[0n": redraw-current-line' &>/dev/null

    function __zoxide_z_complete() {
        # Only show completions when the cursor is at the end of the line.
        [[ ${#COMP_WORDS[@]} -eq $((COMP_CWORD + 1)) ]] || return

        # If there is only one argument, use `cd` completions.
        if [[ ${#COMP_WORDS[@]} -eq 2 ]]; then
            \builtin mapfile -t COMPREPLY < <(
                \builtin compgen -A directory -- "${COMP_WORDS[-1]}" || \builtin true
            )
        # If there is a space after the last word, use interactive selection.
        elif [[ -z ${COMP_WORDS[-1]} ]] && [[ ${COMP_WORDS[-2]} != "${__zoxide_z_prefix}"?* ]]; then
            \builtin local result
            # shellcheck disable=SC2312
            result="$(\command zoxide query --exclude "$(__zoxide_pwd)" --interactive -- "${COMP_WORDS[@]:1:${#COMP_WORDS[@]}-2}")" &&
                COMPREPLY=("${__zoxide_z_prefix}${result}/")
            \builtin printf '\e[5n'
        fi
    }

    \builtin complete -F __zoxide_z_complete -o filenames -- z
    \builtin complete -r zi &>/dev/null || \builtin true
fi

eval "$(zoxide init bash)"

# ==============================================================================
# End of zoxide.sh
# ==============================================================================


# ==============================================================================
#                   End of auto-generated .bashrc content                       
# ==============================================================================

# Tip: Source this file in your interactive shell sessions or ensure it's
# automatically sourced by your shell's main configuration (e.g., .bash_profile).

export BASHRC_GENERATED_ON="2025-05-27 20:35:39 CEST"
