#!/usr/bin/env bash

# ==============================================================================
# generate_bashrc.sh
#
# This script consolidates all .sh files from a specified source directory
# into a single target file (~/.bashrc by default), with comments indicating
# the origin of each section.
#
# Author: Your Name/Simon
# Date: $(date +"%Y-%m-%d %H:%M:%S %Z")
# ==============================================================================

# --- Configuration ---
SOURCE_DIR="${HOME}/scripts/bashrc"
TARGET_FILE="${HOME}/.bashrc"
BACKUP_FILE="${HOME}/.bashrc.bak.$(date +"%Y%m%d_%H%M%S")"

# --- Helper Functions ---
print_header() {
  echo "# =============================================================================="
  echo "# $1"
  echo "# =============================================================================="
  echo "" # Add a blank line for spacing
}

print_footer() {
  echo "" # Add a blank line for spacing
  echo "# =============================================================================="
  echo "# End of $1"
  echo "# =============================================================================="
  echo ""
  echo "" # Extra blank line between sections
}

# --- Main Script ---

# Safety check: Ensure source directory exists
if [ ! -d "$SOURCE_DIR" ]; then
  echo "Error: Source directory '$SOURCE_DIR' not found."
  exit 1
fi

echo "Generating new ${TARGET_FILE} from scripts in ${SOURCE_DIR}..."

# Backup existing .bashrc file
if [ -f "$TARGET_FILE" ]; then
  echo "Backing up existing ${TARGET_FILE} to ${BACKUP_FILE}..."
  cp "$TARGET_FILE" "$BACKUP_FILE"
  if [ $? -ne 0 ]; then
    echo "Error: Failed to create backup. Aborting."
    exit 1
  fi
fi

# Start with a clean target file and add a main header
{
  echo "#!/usr/bin/env bash"
  echo "# =============================================================================="
  echo "#                            ~/.bashrc - Main File                              "
  echo "#                                                                               "
  echo "# This file is auto-generated by the generate_bashrc.sh script.                 "
  echo "# Do not edit this file directly, as your changes will be overwritten.          "
  echo "# Instead, edit the individual .sh files in ${SOURCE_DIR}          "
  echo "# and then re-run the generation script.                                        "
  echo "#                                                                               "
  echo "# Generated on: $(date +"%Y-%m-%d %H:%M:%S %Z")                                    "
  echo "# =============================================================================="
  echo ""
  echo ""
} > "$TARGET_FILE"

# Find all .sh files in the source directory and process them
# Using find and sort to ensure a consistent order (e.g., alphabetical)
find "$SOURCE_DIR" -maxdepth 1 -type f -name "*.sh" -print0 | sort -z | while IFS= read -r -d $'\0' script_file; do
  if [ -f "$script_file" ]; then
    filename=$(basename "$script_file")
    echo "Processing: ${filename}..."

    # Append section header and content to the target file
    {
      print_header "START OF CONFIGURATION FROM: ${filename}"
      cat "$script_file"
      print_footer "${filename}"
    } >> "$TARGET_FILE"
  fi
done

# Add a final closing remark
{
  echo "# =============================================================================="
  echo "#                   End of auto-generated .bashrc content                       "
  echo "# =============================================================================="
  echo ""
  echo "# Tip: Source this file in your interactive shell sessions or ensure it's"
  echo "# automatically sourced by your shell's main configuration (e.g., .bash_profile)."
  echo ""
  echo "export BASHRC_GENERATED_ON=\"$(date +"%Y-%m-%d %H:%M:%S %Z")\""

} >> "$TARGET_FILE"

echo ""
echo "Successfully generated ${TARGET_FILE}!"
echo "A backup of the previous version (if any) was saved to ${BACKUP_FILE}"
echo "Please review the new ${TARGET_FILE} and source it or open a new terminal."
echo "Example: source ~/.bashrc"

exit 0
