# Alacritty - TOML configuration file format.

# DESCRIPTION 
# An example configuration file for Alacritty preconfigured with default values.

# SYNTAX
# Alacritty's configuration file uses the TOML format. 
# The format's specification can be found at https://toml.io/en/v1.0.0.

# GENERAL

# import = ["<string>",]

# Import additional configuration files.
# Imports are loaded in order, skipping all missing files, with the importing file being loaded last. If a field is already present in a previous import, it will be replaced.
# All imports must either be absolute paths starting with /, or paths relative to the user's home directory starting with ~/.

# Example:

# import = [
# "~/.config/alacritty/base16-dark.toml",
# "~/.config/alacritty/keybindings.toml",
# ]

import = [
    "~/.config/alacritty/themes/themes/enfocado_dark.toml",
    "~/.config/alacritty/global.toml",
    "~/.config/alacritty/local.toml",
]
